Improve timeline
openpharma/clinsight pull request #152
Opened 2024-12-20 15:52 UTC by LDSamson

See below for the timeline improvements:

![timeline improvements](https://github.com/user-attachments/assets/e7d880a3-19cc-444c-b9c0-50d3c5b8d69c)

The PR is not yet ready but I think I need some input. I think the main idea is already clearly visible. 

However, I need to add a custom `js` function to trigger the `redraw()` option for the timeline when hovering over an item that has been reviewed, and after clicking on such an item, to get a proper animation in such a case. But I was not yet able to find the right tag for these timeline boxes. Would you able to help with this, @jthompson-arcus ?

2025-01-17 14:46 UTC, LDSamson commented
@jthompson-arcus I've found the issue with the class id and the javascript functions: it cant find the tag because the HTML widget renders late. https://stackoverflow.com/a/62796035/11856430.

I will add a few more tweaks.

2025-01-20 17:11 UTC, LDSamson commented
I added a custom hook for redrawing the timeline on item selection. It looks now like this: 

![clinsight_timeline_improvement](https://github.com/user-attachments/assets/f95d60df-e183-4a79-8b92-bc0f2794d214)

Other customizations:

- The treatment label can be customized using the metadata `treatment_label` setting:
![grafik](https://github.com/user-attachments/assets/7b508f2f-2393-4821-b468-53f3d7d83dc9)
- The on-hover labels are now more consistent and always show the dates first
- The treatment on-hover label also show the treatment dose (if available)

2025-01-29 16:31 UTC, jthompson-arcus requested changes
@LDSamson I like it a lot! In addition to the comments below, I noticed that `metadata.rda` wasn't added. So `clinsight::metadata` doesn't show the treatment label.

2025-01-29 16:31 UTC, jthompson-arcus commented on R/fct_appdata_summary_tables.R
> +      clinsight::add_missing_columns(c("DrugAdminDate", "DrugAdminDose")) |>
Why `clinsight::`?

2025-01-30 14:04 UTC, LDSamson commented on R/app_server.R
> +  treatment_label <- meta$settings$treatment_label %||% "\U1F48A T\U2093"
I moved it to `get_metadata()` and documented it. I also impute it now in `mod_timeline_server()` so that it will not crash on older metadata files where treatment label is missing (a bit redundant indeed, but just to be sure).

2025-01-30 14:04 UTC, LDSamson commented on R/fct_appdata_summary_tables.R
> +      clinsight::add_missing_columns(c("DrugAdminDate", "DrugAdminDose")) |>
oops

2025-01-30 14:58 UTC, LDSamson commented
@jthompson-arcus I also added a few tests

2025-01-30 20:07 UTC, jthompson-arcus approved these changes
LGTM

2025-01-30 20:08 UTC, merged